import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { label: "Docs", to: "/docs" },
  { label: "Todos", to: "/todos" },
  { label: "Home", to: "/" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <header className="border-b-black border-[1px]">
          <ul className="flex items-center gap-5 px-3 py-2" role="navigation">
            {links.map((link) => (
              <li className="hover:text-sky-600" key={link.label}>
                <Link href={link.to}>{link.label}</Link>
              </li>
            ))}
          </ul>
        </header>
        <main className="h-full">{children}</main>
      </body>
    </html>
  );
}
